### ISSUE TITLE
Eduroam Darmstadt

### ISSUE THREAD

**Issue by noggynoggy** [Keksgesicht/nixos-config#1]
Hey there, I see you got eduroam working with your config. The [method](https://nx2.site/eduroam-nixos) I used before doesn't work with the TUDa because [cat.eduroam.org](https://cat.eduroam.org/) does not show the p12 option. Could you give me some direction on how you did it? 

Thank you in advance. : )

**Comment by Keksgesicht** [comment]
I have not heard about the method you mentioned, but my university has some [information](https://www.hrz.tu-darmstadt.de/support_und_anleitungen/hrz_anleitungen/wlan_anleitungen/index.en.jsp) what you have to fill in to connect to the APs. This can also be found in my NetworkManager config under [files/linux-root/etc/NetworkManager/system-connections/eduroam.nmconnection](https://github.com/Keksgesicht/nixos-config/blob/unstable/files/linux-root/etc/NetworkManager/system-connections/eduroam.nmconnection):
- The `ca-cert` is part of `pkgs.cacert.unbundled`
  - `unbundled` not needed, but could provide more explicit security
  - I did some wierd stuff to produce nicer names in /etc.. (see [system/network/desktop/default.nix#L71](https://github.com/Keksgesicht/nixos-config/blob/unstable/system/network/desktop/default.nix#L71))
- `identity` (or username) is included through some hidden file, but just use there what the [IDM WLAN Accounts](https://www.idm.tu-darmstadt.de/) provide you with. See also instrunctions in the first information link.
- The password ist filled in by KDE Wallet Manager, but any other key store should work.

Not sure what information I could provide you else. If my config does not help you, you probably have to contact the HRZ directly.

**Comment by noggynoggy** [comment]
Starting with your idea I've deveoped a working solution and updated my tutorial with a new section

https://nx2.site/eduroam-nixos#steps-for-the-wi-fi-eduroam

Thaks for your help!
